### ISSUE TITLE
There is no extension able to load the configuration for "pimcore.navigation.builder"

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/frontend-permission-toolkit#1]
When I add 
```yml
pimcore.navigation.builder:
    class: FrontendPermissionToolkitBundle\CoreExtensions\Navigation\Builder
    arguments: ['@pimcore.http.request_helper']
    public: false
    calls:
      - [setService, ['@bundle.frontendpermissiontoolkit.service']]
      - [setCurrentUser, ['@security.token_storage']]
```
to my app/config/config.yml I get the error:
```
FileLoaderLoadException
There is no extension able to load the configuration for "pimcore.navigation.builder" (in /var/www/.../web/app/config/config.yml). Looked for namespace "pimcore.navigation.builder", found "framework", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "cmf_routing", "presta_sitemap", "security", "web_profiler", "sensio_distribution", "debug", "pimcore_admin", "pimcore", "pimcore_generator", "hamburg_at_work_website", "pimcore_customer_management_framework", "pimcore_ecommerce_framework", "blackbit_eventbrite", "blackbit_pim", "blackbit_elastic_search", "opt_in_mail", "frontend_permission_toolkit", "app", "hwi_oauth", "httplug" in /var/www/.../web/app/config/config.yml (which is being imported from "/var/www/.../web/app/config/config_dev.yml").
```
